name: healthcare-appointments

services:
  db:
    image: postgres:17-alpine
    env_file:
      - ../infrastructure/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    image: smjxpro/healthcare-appointments-api:latest
    build:
      context: ../backend/Healthcare.Appointments
      dockerfile: src/Healthcare.Appointments.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "7001:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:
